# Generated bycitystatistic Django 4.1.5 on 2023-01-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_salary', models.FileField(upload_to='', verbose_name='Динамика уровня зарплат по годам')),
                ('year_count', models.FileField(upload_to='', verbose_name='Динамика количества вакансий по годам')),
                ('city_salary', models.FileField(upload_to='', verbose_name='Динамика зарплат по городам')),
                ('city_part', models.FileField(upload_to='', verbose_name='Доля ваканский по городам')),
                ('year_skils', models.FileField(upload_to='', verbose_name='Топ-10 навыков по годам')),
            ],
        ),
    ]
