# Generated by Django 4.1.5 on 2023-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByCityStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary', models.CharField(max_length=100, verbose_name='Город (для зарплат)')),
                ('salary', models.IntegerField(verbose_name='Уровень зарплат по городам')),
                ('city_part', models.CharField(max_length=100, verbose_name='Город (для доли вакансий)')),
                ('part', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Доля вакансий по городам')),
            ],
        ),
    ]
