# Generated by Django 4.1.5 on 2023-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bycitystatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skills', models.TextField(max_length=250, verbose_name='Топ-10 Навыков')),
            ],
        ),
        migrations.RenameField(
            model_name='images',
            old_name='year_skils',
            new_name='year_skills',
        ),
    ]
